from flask import Flask, request, redirect, url_for, render_template, send_from_directory, jsonify, Response
from werkzeug.utils import secure_filename
import os
import json
import uuid

# Import the logic and configuration
from config_and_logic import UPLOAD_FOLDER, ALLOWED_EXTENSIONS, allowed_file, generate_progress_stream, PROCESSING_STEPS

app = Flask(__name__)
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
app.config['MAX_CONTENT_LENGTH'] = 16 * 1024 * 1024  # 16 MB limit

# Ensure the upload directory exists and create it if necessary
os.makedirs(UPLOAD_FOLDER, exist_ok=True) 

# --- Routes ---

@app.route('/', methods=['GET'])
def index():
    """Renders the main upload page, passing the processing steps for the progress list."""
    return render_template('index.html', steps=PROCESSING_STEPS) 

@app.route('/upload', methods=['POST'])
def upload_file():
    """
    Handles file upload via AJAX. Returns a JSON response with the stream URL 
    to initiate the SSE connection on the client side.
    """
    if 'file' not in request.files:
        return jsonify({"success": False, "message": "No file part"}), 400
    
    file = request.files['file']
    
    if file.filename == '':
        return jsonify({"success": False, "message": "No selected file"}), 400
        
    if file and allowed_file(file.filename):
        # Generate a unique, secure filename
        original_filename = secure_filename(file.filename)
        unique_prefix = str(uuid.uuid4())
        
        filename, extension = os.path.splitext(original_filename)
        unique_filename = f"{unique_prefix}_{filename}{extension}"
        
        filepath = os.path.join(app.config['UPLOAD_FOLDER'], unique_filename)
        file.save(filepath)
        
        # Return JSON success message with the stream URL
        return jsonify({
            "success": True, 
            "message": "File uploaded successfully. Starting processing stream...",
            "stream_url": url_for('stream', filename=unique_filename) 
        }), 200
    
    return jsonify({"success": False, "message": "File type not allowed"}), 400


@app.route('/stream/<filename>')
def stream(filename):
    """Streams the progress updates to the client via Server-Sent Events (SSE)."""
    filepath = os.path.join(app.config['UPLOAD_FOLDER'], filename)
    
    if not os.path.exists(filepath):
        # If the file is missing, send a formatted SSE error immediately
        error_message = {'status': 'error', 'step_id': 'initial', 'message': 'File not found to process. Please try uploading again.'}
        return Response(
            f"event: update\ndata: {json.dumps(error_message)}\n\n",
            mimetype='text/event-stream'
        )
    
    # Use Response to stream the content generated by the logic function
    return Response(
        generate_progress_stream(filepath),
        mimetype='text/event-stream'
    )

@app.route('/download/<path:filename>')
def download_file(filename):
    """Allows client to download the generated JSON files."""
    try:
        return send_from_directory(app.config['UPLOAD_FOLDER'], filename, as_attachment=True)
    except FileNotFoundError:
        return "File not found.", 404

# --- Run Application ---

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)